baseurl: ""
permalink: pretty
markdown: rdiscount
exclude: [Gemfile,Gemfile.lock,LICENSE,README.md]
prose:
  rooturl: '_posts'
  siteurl: 'http://gwaba.github.io'
  relativeLinks: 'http://gwaba.github.io/links.jsonp'
  media: '_posts/media'